[build]
#command = "rm -rf __obsidian __site && git clone https://github.com/ClementBobin/obsidian-zola.git __site && __site/run.sh || true"
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ClementBobin/obsidian-zola.git __site && __site/run.sh"
publish = "public" 

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = "Dive into my mind 🚀"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "A labyrinth of thoughts, ideas, and code."
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "home"
# (Optional) Site title on landing page
LANDING_TITLE = "Mirage's Archive 🌌"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/ClementBobin/obsidian-markdown-SIO2023-2024"
# (Optional) Site title in navbar
SITE_TITLE = "Mirage's Notebook 📖"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "Mirage's Notebook"
# (REQUIRED) Netlify site URL
SITE_URL = "https://mirage-docs.netlify.app/"
# (Optional) Site Timezone
TIMEZONE = "Europe/Paris"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "weight"
# (Optional) Google Analytics Measurement ID
GANALYTICS = "G-1JP5QCQTEW"
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = "true"
# (Optional, default blank) Additional footer content.
FOOTER = "© 2025 Mirage - "
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "main"
# (Optional) visjs graph options. Can remove if desired.
GRAPH_OPTIONS = """
        {
			autoResize: true,
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
				roundness: 1
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
				solver: "forceAtlas2Based",
				stabilization: false
        	},
        }
        """
